name: Node.js Package

on:
  release:
    types: [created] # 仅当创建 Release 时触发
  push:
    branches:
      - main         # 或保留，仅当 push 到 main 分支时触发

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'
      - name: Bump version (optional)
        run: npm version patch # 自动更新版本号
      - name: Rollup build
        run: npm run build
      - name: Check git status
        run: git status
      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
